// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _1_DAL_Layer.DataBaseContext;

namespace _1_DAL_Layer.Migrations
{
    [DbContext(typeof(DBcontext))]
    [Migration("20210930150021_Fisrt")]
    partial class Fisrt
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("_1_DAL_Layer.Entitys.Hang", b =>
                {
                    b.Property<string>("MaHang")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("AnhHang")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("DonGiaBan")
                        .HasColumnType("int");

                    b.Property<int>("DơnGiaNhap")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ID_Hang")
                        .HasColumnType("int");

                    b.Property<string>("Ma_NhanVien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NhanVienMa_NhanVien")
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenHang")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaHang");

                    b.HasIndex("NhanVienMa_NhanVien");

                    b.ToTable("Hangs");
                });

            modelBuilder.Entity("_1_DAL_Layer.Entitys.KhachHang", b =>
                {
                    b.Property<string>("SDT")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("GioiTinh")
                        .HasColumnType("int");

                    b.Property<string>("Ma_NhanVien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NhanViensMa_NhanVien")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenKhachHang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SDT");

                    b.HasIndex("NhanViensMa_NhanVien");

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("_1_DAL_Layer.Entitys.NhanVien", b =>
                {
                    b.Property<string>("Ma_NhanVien")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ID_NhanVien")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenNhanVien")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("VaiTro")
                        .HasColumnType("int");

                    b.HasKey("Ma_NhanVien");

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("_1_DAL_Layer.Entitys.Hang", b =>
                {
                    b.HasOne("_1_DAL_Layer.Entitys.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NhanVienMa_NhanVien");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("_1_DAL_Layer.Entitys.KhachHang", b =>
                {
                    b.HasOne("_1_DAL_Layer.Entitys.NhanVien", "NhanViens")
                        .WithMany()
                        .HasForeignKey("NhanViensMa_NhanVien");

                    b.Navigation("NhanViens");
                });
#pragma warning restore 612, 618
        }
    }
}
