// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _1_DAL_Layer.DataBaseContext;

namespace _1_DAL_Layer.Migrations
{
    [DbContext(typeof(DBcontext))]
    [Migration("20211010153632_update-table-1")]
    partial class updatetable1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("_1_DAL_Layer.Entities.Customer_Order", b =>
                {
                    b.Property<string>("CO_Code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CustomerCt_PhoneNumber")
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ep_Code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Total_Money")
                        .HasColumnType("int");

                    b.HasKey("CO_Code");

                    b.HasIndex("CustomerCt_PhoneNumber");

                    b.HasIndex("Ep_Code");

                    b.ToTable("Customer_Order");
                });

            modelBuilder.Entity("_1_DAL_Layer.Entitys.Customer", b =>
                {
                    b.Property<string>("Ct_PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Ct_Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ct_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Ct_Sex")
                        .HasColumnType("int");

                    b.Property<string>("Ep_Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Ct_PhoneNumber");

                    b.HasIndex("Ep_Code");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("_1_DAL_Layer.Entitys.Employee", b =>
                {
                    b.Property<string>("Ep_Code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Ep_Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ep_Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Ep_Id")
                        .HasColumnType("int");

                    b.Property<string>("Ep_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ep_Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Ep_Role")
                        .HasColumnType("int");

                    b.Property<bool>("Ep_Status")
                        .HasColumnType("bit");

                    b.Property<bool>("Ep_StatusPassword")
                        .HasColumnType("bit");

                    b.HasKey("Ep_Code");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("_1_DAL_Layer.Entitys.Products", b =>
                {
                    b.Property<string>("Prd_Code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Ep_Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("Img_Barcode")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Prd_ExportPrice")
                        .HasColumnType("int");

                    b.Property<int>("Prd_Id")
                        .HasColumnType("int");

                    b.Property<byte[]>("Prd_Image")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Prd_ImportPrice")
                        .HasColumnType("int");

                    b.Property<string>("Prd_Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Prd_Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Prd_Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Prd_Sale")
                        .HasColumnType("int");

                    b.HasKey("Prd_Code");

                    b.HasIndex("Ep_Code");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("_1_DAL_Layer.Entities.Customer_Order", b =>
                {
                    b.HasOne("_1_DAL_Layer.Entitys.Customer", null)
                        .WithMany("Customer_Orders")
                        .HasForeignKey("CustomerCt_PhoneNumber");

                    b.HasOne("_1_DAL_Layer.Entitys.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("Ep_Code");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("_1_DAL_Layer.Entitys.Customer", b =>
                {
                    b.HasOne("_1_DAL_Layer.Entitys.Employee", "Employee")
                        .WithMany("Customer")
                        .HasForeignKey("Ep_Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("_1_DAL_Layer.Entitys.Products", b =>
                {
                    b.HasOne("_1_DAL_Layer.Entitys.Employee", "Employee")
                        .WithMany("Products")
                        .HasForeignKey("Ep_Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("_1_DAL_Layer.Entitys.Customer", b =>
                {
                    b.Navigation("Customer_Orders");
                });

            modelBuilder.Entity("_1_DAL_Layer.Entitys.Employee", b =>
                {
                    b.Navigation("Customer");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
