// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _1_DAL_Layer.DataBaseContext;

namespace _1_DAL_Layer.Migrations
{
    [DbContext(typeof(DBcontext))]
    partial class DBcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("_1_DAL_Layer.Entitys.Hang", b =>
                {
                    b.Property<string>("MaHang")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("AnhHang")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("DonGiaBan")
                        .HasColumnType("int");

                    b.Property<int>("DonGiaNhap")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ID_Hang")
                        .HasColumnType("int");

                    b.Property<string>("Ma_NhanVien")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenHang")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaHang");

                    b.HasIndex("Ma_NhanVien");

                    b.ToTable("Hangs");
                });

            modelBuilder.Entity("_1_DAL_Layer.Entitys.KhachHang", b =>
                {
                    b.Property<string>("SDT")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("GioiTinh")
                        .HasColumnType("int");

                    b.Property<string>("Ma_NanVienMa_NhanVien")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenKhachHang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SDT");

                    b.HasIndex("Ma_NanVienMa_NhanVien");

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("_1_DAL_Layer.Entitys.NhanVien", b =>
                {
                    b.Property<string>("Ma_NhanVien")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ID_NhanVien")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenNhanVien")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<bool>("TrangThaiMatKhau")
                        .HasColumnType("bit");

                    b.Property<int>("VaiTro")
                        .HasColumnType("int");

                    b.HasKey("Ma_NhanVien");

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("_1_DAL_Layer.Entitys.Hang", b =>
                {
                    b.HasOne("_1_DAL_Layer.Entitys.NhanVien", "NhanVien")
                        .WithMany("Hangs")
                        .HasForeignKey("Ma_NhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("_1_DAL_Layer.Entitys.KhachHang", b =>
                {
                    b.HasOne("_1_DAL_Layer.Entitys.NhanVien", "Ma_NanVien")
                        .WithMany("KhachHangs")
                        .HasForeignKey("Ma_NanVienMa_NhanVien");

                    b.Navigation("Ma_NanVien");
                });

            modelBuilder.Entity("_1_DAL_Layer.Entitys.NhanVien", b =>
                {
                    b.Navigation("Hangs");

                    b.Navigation("KhachHangs");
                });
#pragma warning restore 612, 618
        }
    }
}
